apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-prod-2-configmap
  namespace: nginx
data:
  default.conf: |
    server {
      listen 80;
      server_name  _;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
    }
