apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-prod-2-vol-1
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 10.20.0.6
    path: "/mnt/store/app-pv/nginx-prod-2-vol-1"
