global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus-prod-1'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Docker Server in Production
  - job_name: 'cadvisor-prod-1'
    scrape_interval: 5s
    static_configs:
      - targets: [cadvisor-prod-1:8080]

  - job_name: 'cadvisor-prod-2'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 5s
    static_configs:
      - targets: [cadvisor-prod-2.srv-prod-2.home.clcreative.de:443]


  # Scrape Production Servers
  - job_name: 'srv-prod-1'
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-1.home.clcreative.de:9100]

  - job_name: 'srv-prod-2'
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-2.home.clcreative.de:9100]

  - job_name: 'srv-prod-3'
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-3.home.clcreative.de:9100]

  - job_name: 'srv-prod-4'
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-4.home.clcreative.de:9100]

  - job_name: 'srv-prod-5'
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-5.home.clcreative.de:9100]

  - job_name: 'srv-prod-6'
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-6.home.clcreative.de:9100]

  - job_name: 'srv-prod-7'
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-7.home.clcreative.de:9100]

  # Example job for node_exporter
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']

  # Example job for cadvisor
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
