apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-prod-1-certificate
  namespace: argocd
spec:
  secretName: argocd-prod-1-tls-secret
  issuerRef:
    name: certmanager-prod-1-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - argocd-prod-1.kube-prod-1.home.clcreative.de
