apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-prod-1-certificate
  namespace: authentik
spec:
  secretName: authentik-prod-1-tls
  issuerRef:
    name: certmanager-prod-1-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - authentik-prod-1.kube-prod-1.home.clcreative.de
