apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-prod-1-pvc
  namespace: portainer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi
  volumeName: portainer-prod-1-pv
