apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: certmanager-prod-1-clusterissuer
spec:
  acme:
    email: info@clcreative.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: certmanager-prod-1-clusterissuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: info@clcreative.de
            apiTokenSecretRef:
              name: certmanager-prod-1-token
              key: api-token